/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_TestJni */

#ifndef _Included_com_example_myapplication_TestJni
#define _Included_com_example_myapplication_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_TestJni
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myapplication_TestJni_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
